CREATE TABLE IF NOT EXISTS projects (id BIGSERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS items (id BIGSERIAL PRIMARY KEY,project_id BIGINT NOT NULL REFERENCES projects(id),title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_events (id BIGSERIAL PRIMARY KEY,actor_user_id BIGINT,action TEXT NOT NULL,resource TEXT,details JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
